language: python

#env:
#  matrix:
#    - TOXENV=py27-ansible24-install
#    - TOXENV=py27-ansible24-remove
#    - TOXENV=py27-ansible25-install
#    - TOXENV=py27-ansible25-remove

# Handle git submodules yourself
git:
  submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

services:
  - docker

python:
  - 2.7

install:
  - pip install tox
  - pip install tox-travis

script:
  - tox

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
