---
- include_tasks: install-dnf.yml
  when: ansible_distribution_version|int >= 23
  tags:
    - copr-repository-install-dnf

- include_tasks: install-yum.yml
  when: ansible_distribution_version|int <= 22
  tags:
    - copr-repository-install-yum