---
- name: install fedora copr plugin (dnf)
  package:
    name: dnf-command(copr)
    state: present

- name: install fedora copr repository (dnf)
  command: "dnf -y copr enable {{ copr_repository }}"
  args:
    creates: "{{ copr_repository_repofile }}"
    warn: no