---
- name: converge
  hosts: all
  gather_facts: True
  tasks:
    - name: test repository removal
      include_role:
         name: ansible-role-copr-repository
      vars:
        copr_repository: "abn/keycloak"
        copr_repository_action: "remove"